### ISSUE TITLE
Add events when reflowing grid items on window resize

### ISSUE THREAD

**Issue by SlapBassist** [swiety85/angular2gridster#115]
It would be great if there was an event that indicated that the grid was reflowed, sizes recalculated etc. I have content within the grid items that need to be told what the width/height changes are in order to draw themselves properly.

**Comment by swiety85** [comment]
Hi, it's missing. I found no good way to reach this point. I will try to provide dedicated event in nearest release.

**Comment by SlapBassist** [comment]
Any update on this feature? Would be great to see it soon.

**Comment by swiety85** [comment]
Done in v. 0.6.9. Use `reflow` event on Gridster component. More info in [wiki](https://github.com/swiety85/angular2gridster/wiki/API-Documentation#outputs).

**Comment by SlapBassist** [comment]
Great! What's the best way to get the sizing of each grid item once I listen for this event?

**Comment by swiety85** [comment]
I'm not sure if I got you right.
One solution could be to provide method that resize the content according to the parent element size e.g. `updateWidth`. This method would have to be called from parent component that renders Gridster e.g.
```js
@ViewChildren(YourCustomComponent) customComponents: YourCustomComponent;
...
onGridsterReflow(event) {
    customComponents.forEach((component) => {
        component.updateWidth();
    });
}
```
Another way could be to provide service that would be mediator between component that renders gridster and nester components that needs to react on gridster actions.
In case of any more questions or suggestions, write.

**Comment by Eloi-Marin** [comment]
After testing quite a bit, I find that _reflow_ output, as well as _change_ output or any other output, are not being triggered when I change x-y-w-h parameters for a grister-item programatically, instead of manually dragging or resizing. The idea is: I am using an immutable store, together with *ngFor with trackBy with a proper id for each item. Then, with a click of a button I change the array of widgets I am providing to the gridster-item *ngFor, where some items are same as before, others have moved, others have changed. Angular2gridster successfuly repositions and resizes gridster-items, but doens't trigger any event that warns me it has finished respositioning/resizing.

It would be really useful I could hook into that event because I would use it to reflow the content inside each gridster-item that has resized to the new height and width of the gridster-item.

I will appreciate any help or indication if I am missing anything, thank you !
