### ISSUE TITLE
Strange drop and load behavior

### ISSUE THREAD

**Issue by Blackbaud-XandraHarrison** [swiety85/angular2gridster#157]
When upgrading from around 0.6 to the current gridster version, my team noticed some strange behavior developed related to dropping widgets in the grid and loading widgets in the grid. The layout seemed to populate incorrectly based on the coordinates given by the drop action. By poking around in the demo, we came to add the following lines to our solution:

`let keyx: (keyof Widget) = DashboardEditorComponent.X_PROPERTY_MAP[this.gridsterOptions.breakpoint];
let keyy: (keyof Widget) = DashboardEditorComponent.Y_PROPERTY_MAP[this.gridsterOptions.breakpoint];
newWidget[keyx] = tile.x;
newWidget[keyy] = tile.y;`

This seems like a strange step to need to take manually. Thoughts?

**Comment by swiety85** [comment]
Hi,
I suppose you use `responsiveOptions`. In this case you use different coords props for different breakpoints (`[(x)]="widget.x" [(y)]="widget.y" [(xSm)]="widget.xSm" [(ySm)]="widget.ySm"`...).
The case now is, when you push new object to your list, girdster-item reads coords properties for current breakpoint e.g. if current is 'sm' then it uses `widget.xSm` and `widget.ySm`.
If you put coords to `widget.x` and `widget.y`, this position will try to be applied on the smallest breakpoint, and for other breakpoint it will apply positions automatically.
From that reason expected behaviour is to put new item coords in properties dedicated for current breakpoint.
In version 0.6, it worked, but it was a bug and generates some serious issues.
I know that it can be a bit confusing, but for now I don't have any other idea.
I hope I've clarified it a little.
If you have any more questions or suggestions, fill free to write.
