### ISSUE TITLE
Second Instance of Widget Overriding Data of First

### ISSUE THREAD

**Issue by michaelblxck** [swiety85/angular2gridster#175]
I am adding widgets to a dashboard by pushing a widget component to a dashboard array. The dashboard array is an observable, so gridster's html is being refreshed each time a new widget is being pushed. If I push a graph widget to the dashboard that graphs data from source 1 it works fine. The graph widget refers to a service for which source to use, as set by the user in an add widget function. If I try pushing a second instance of the graph widget that graphs data from source 2, both instances now refer to source 2 for updates. This is because the user has updated the service to use source 2, and when the second graph widget is pushed to the dashboard, both of the instances are re rendered and look to the service, now holding the value for source 2. How do I keep the first instance of graph widget looking at source 1 and the second instance looking at source 2? I'm new to angular, so I'm not sure how to do this. I've looked around and seen that maybe NgComponentOutlet or localStorage might be helpful. Any help is much appreciated.

**Comment by swiety85** [comment]
Hi, as far as I can guess, you have list of widgets that rely on different source of data. Maybe solution would be to pass source to the widget object (in the "dashboard array").
It's really hard for me to guess what is the problem, because I don't understand the case. I would need at least some code examples to help better.
