### ISSUE TITLE
Rest all widgets/grid items to their initial positions

### ISSUE THREAD

**Issue by yahyazini** [swiety85/angular2gridster#199]
Question: 
Hi, I have an issue where I want to create an edit mode on a dashboard to enable drag and drop and have a cancel button so that the widgets return to their initial position in case the user doesn't want to update them.

I'm keeping track of the initialWidgets which is an array that snapshots the widgets when the dashboard first goes into editMode and on hitting cancel I'm setting wigets = initialWidgets.

I tried the reload and reflow methods but it doesn't seem to work

**Comment by swiety85** [comment]
Hi,
the approach to achieve this feature seams to be correct and should work.
You should remember only to not use simple `=` to store initialWidgets, but create a copy of the existing widgets e.g.
```js
this.initialWidgets = this.widgets.map(widget => ({...widget}));
```
If you use only `=` your widgets stores references to the same widget objects. It means that when widgets from `widgets` array are modified, the widgets from `initialWidgets` are modified as well, because they are the same objects.
I've tested this feature on demo page and it works for me. I used above code to copy widgets in `ngOnInit` and  `resetWidgets` method.

**Comment by yahyazini** [comment]
That was exactly my issues. I was using initialWidgets  = widgets.slice(0) to get rid of the reference from the widget but that wasn't working since I stored the grid props one level down in widget.gridOptions. Object assigning this latter fixed the issue. Thank you!
