### ISSUE TITLE
How do widgets takes up empty space in the grid even when (x,y) position is specified in widget object

### ISSUE THREAD

**Issue by ndmello** [swiety85/angular2gridster#222]

**Comment by swiety85** [comment]
Hi, I assumed that you use `responsiveOptions`. In this case, you are forced to use different position properties for different breakpoints. Most probably you set `x` and `y` properties that are used only on mobiles For desktop other props are used, depends on window width: `xSm`, `ySm`, `xMd`, `yMd`, `xLg`, `yLg`, `xXl`, `yXl`.
Have a look how this problem is solved in [the demo](https://github.com/swiety85/angular2gridster/blob/master/demo/src/app/app.component.ts#L182).
Write in case of any more questions.

**Comment by ndmello** [comment]
Thank you! That worked!
