### ISSUE TITLE
How to dynamically set margin between gridster Item

### ISSUE THREAD

**Issue by salahatwa** [swiety85/angular2gridster#349]
How to dynamically set margin between gridster Item ,
since in Dashboard view it shouldn't set margin to be 0

**Comment by swiety85** [comment]
By default `.gridster-item-inner` class is responsible for defining a margin between items.
Since this element is not accessible from outside of GridsterItem, you can not easily set dynamic styles.
As a simple solution, I would suggest defining a margin in the root element placed in the GridsterItems component content, and in CSS file remove spacing and background from `.gridster-item-inner`.
