### ISSUE TITLE
Dragging performance with items with heavy content

### ISSUE THREAD

**Issue by tw2as** [swiety85/angular2gridster#76]
When we have few gridster items with large components inside, dragging an element seems to be a bit slow. At the same time adding a new element by "Drag me (clone)" (which is an empty item with "New widget") around those heavy items seems to render quicker.

Do you have any solution to something like that? Possibly during dragging replacing a gridster item with a grey empty item which only has a title (similar to adding a new item by "Drag me (clone)") would improve it.

I can replicate that on the demo page by replacing "test works!" with a JSON (50kB+) in few components.

**Comment by swiety85** [comment]
Hi, I'm not sure for now but it can be related with the way item position is updating while dragging. Currently css "width" and "height" properties are updating but there is a plan to use CSS transform that can improve rendering performance significantly.
Other then that I will try to reproduce your problem as you described and check if there can be other reason..

**Comment by swiety85** [comment]
I tried to reproduce your problem. 
First I tried to but 5K images in GridsterItem component content. This does not generate much problems with performance. Time to rendering huge images was big, but this is understandable. Dragging items generates no significant problems.
Then I put "really huge" JSON object with `| json` angular pipe in each item. From this point it was laggy in two points: drag start and drop. Only for these points angular changeDetection is executed in gridster (except of init or window resize). This is also understandable, because changeDetection was running and angular pipe reformats huge JSON object. This is rather not related with Gridster - the same lagging in this case could be generated while typing in the input.
Never the less I put some effort to improve performance of Angular2Gridster:
* prevent performance issues while dragging item with selected text inside
* get rid of getBoundingRect in drag event
* add option useCSSTransforms for more effective rendering while dragging item

I would suggest to upgrade to v 0.6.7 and set option `useCSSTransforms` to `true`. I hope the it will help at least a little bit.
Write in case of any question.
