### ISSUE TITLE
Setting specific width or height for grid 

### ISSUE THREAD

**Issue by vistajess** [swiety85/angular2gridster#77]
Good day, I just want to ask if there is an option for setting specific with by pixel or etc.

Based on the photo below, the grid basically has options `height : 1` and `width : 6` and its approximately 100px by height.  I want to set the base height of the grid maybe 50px or what ever I like.  I am creating sort of a dashboard thing then I am concern for small details such as texts or images.

Is that possible?

![image](https://user-images.githubusercontent.com/12708502/28662330-56d811cc-72ec-11e7-9859-4728e63f98ee.png)

**Comment by swiety85** [comment]
Hi, I'm not sure if I got you right. Do you want to set fixed height of "grid cell" or whole "grid" (dashboard)? Do you use  direction='vertical'?
Gridster automatically sets height of "dashboard" using available width, "lanes" and "widthHeightRatio" (default=1) - for now girdster is not supporting fixed height - that the items heights will adjust its sizes to available space. But it's planned.
You can try to manipulate widthHeightRatio option.
If your dashboard has 200px width, lanes=4 and widthHeightRatio=1, then height of items will be as follows: h=1 => 50px, h=2 => 100px, etc.
If you want to make items height smaller then adjust widthHeightRatio e.g.
widthHeightRatio=2
 h=1 => 25px, h=2 => 50px, etc.
If you have option "shrink=true" and direction='vertical' then "dashboard" height will adjust to items on the board.
I hope this helps you, otherwise please write more detailed questions and will do my best to give you the answer.

**Comment by vistajess** [comment]
Thanks for the response , I'm pertaining to `grid cell` hehe sorry for the confusion.
I will try what you had suggested to me very well explained. I think widthHeightRatio is pretty cool.

Thanks a lot, God bless.

**Comment by vistajess** [comment]
The `widthHeightRatio` solved my problem :) thanks
