### ISSUE TITLE
Anti-Pattern API

### ISSUE THREAD

**Issue by amcdnl** [swiety85/angular2gridster#97]
The API is somewhat of a anti-pattern for Angular. There is a certain expectation that you can just set properties in angular and it react. My proposal would be rather than having a global `options` object, have individual inputs and then use getters/setters to react in the code.

For example:

```
<gridster [resizable]="isResizable">
   ...
</gridster>
```

then in the code you can react like:

```
class Foo {
   set resizable(val: boolean) {
      this._resizable = val;
      this.update();
   }
  get resizable() { return this._resizable; }
  private _resizable: boolean = true;
}
```

with this code I was able to remove the `setOption`, enable two-way binding, provide a more declarative syntax in the template and enable OnPush CD with reactive nature which is what ppl expect from Angular components.

**Comment by swiety85** [comment]
I was also considering this when I started implementing this component, but I think in case of huge configuration object (especially with nested structure, because of different configuration for different breakpoints) it make no sense and would rather not work.
But never the less thanx for suggestion.
